version: "3.9"

x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "my_service"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_USER: "postgres"

x-rabbitmq-variables: &x-rabbitmq-variables
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "4"
  # App
  APP_NAME: "api-gateway"
  APP_VERSION: "1.0.0"
  # HTTP settings
  HTTP_PORT: "8080"
  HTTP_USE_PREFORK_MODE: "false"
  # Logger
  LOG_LEVEL: "debug"
  # gRPC
  GRPC_PORT: "8081"
  # RMQ
  RMQ_RPC_SERVER: "rpc_server"
  RMQ_RPC_CLIENT: "rpc_client"
  RMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  # Metrics
  METRICS_ENABLED: "true"
  # Swagger
  SWAGGER_ENABLED: "true"


services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      app_network:
        aliases:
          - db

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1-management
    environment:
      <<: *x-rabbitmq-variables
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      app_network:
        aliases:
          - rabbitmq.lvh.me

  app:
    container_name: api-gateway
    platform: linux/amd64
    pid: "host"
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    networks:
      app_network:
        aliases:
          - api-gateway

  nginx:
    image: nginx:1.29.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
      - app
    networks:
      app_network:
        aliases:
          - nginx.lvh.me


networks:
  app_network:
    external: true


volumes:
  db_data:
  rabbitmq_data:
